name: Astronomer CI - Deploy code to main Deployment

on:
  push:
    branches:
      - main

env:
  ## Set your API token as a GitHub secret
  ASTRO_API_TOKEN: ${{ secrets.PROD_ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy code to main Deployment
      uses: astronomer/deploy-action@v0.2
      with:
        deployment-id: clpufr6n25077851uum5zan7b25
